--
-- PostgreSQL database dump
--
CREATE DATABASE reviewdb;
\connect reviewdb;
-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-08-12 17:17:25

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 49892)
-- Name: comment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comment (
    id bigint NOT NULL,
    review_date timestamp(6) without time zone NOT NULL,
    book_id character varying(255) NOT NULL,
    content character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL
);


ALTER TABLE public.comment OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 49891)
-- Name: comment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 49900)
-- Name: rate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rate (
    score integer NOT NULL,
    id bigint NOT NULL,
    review_date timestamp(6) without time zone NOT NULL,
    book_id character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL
);


ALTER TABLE public.rate OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 49899)
-- Name: rate_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 33190)
-- Name: review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review (
    id bigint NOT NULL,
    book_id character varying(255) NOT NULL,
    comment character varying(255),
    rating integer NOT NULL,
    review_date timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL
);


ALTER TABLE public.review OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 33189)
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4859 (class 0 OID 49892)
-- Dependencies: 220
-- Data for Name: comment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comment (id, review_date, book_id, content, user_id) FROM stdin;
4	2025-08-11 01:25:26.809866	978-0747532743	Test comment	88b95c38-999f-4ddd-926b-3169c95350d5
5	2025-08-11 01:28:59.426721	978-0747532743	Test comment	88b95c38-999f-4ddd-926b-3169c95350d5
\.


--
-- TOC entry 4861 (class 0 OID 49900)
-- Dependencies: 222
-- Data for Name: rate; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rate (score, id, review_date, book_id, user_id) FROM stdin;
\.


--
-- TOC entry 4857 (class 0 OID 33190)
-- Dependencies: 218
-- Data for Name: review; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.review (id, book_id, comment, rating, review_date, user_id) FROM stdin;
1	978-0747532743	comment1	5	2025-03-24 20:10:05.499705	user1
8	978-0747532743	comment2	1	2025-03-28 17:22:23.176307	user2
10	978-0747532743	comment2	5	2025-03-28 17:29:42.363614	user1
12	978-0747532743	comment2	5	2025-03-28 19:54:53.657112	user1
13	978-0747532743	comment2	5	2025-03-28 19:55:50.912027	user1
14	978-0747532743	comment2	5	2025-03-28 19:57:54.441261	user1
15	978-0747532743	comment2	5	2025-03-28 20:06:52.645619	user1
\.


--
-- TOC entry 4867 (class 0 OID 0)
-- Dependencies: 219
-- Name: comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comment_id_seq', 6, true);


--
-- TOC entry 4868 (class 0 OID 0)
-- Dependencies: 221
-- Name: rate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rate_id_seq', 1, false);


--
-- TOC entry 4869 (class 0 OID 0)
-- Dependencies: 217
-- Name: review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.review_id_seq', 15, true);


--
-- TOC entry 4708 (class 2606 OID 49898)
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);


--
-- TOC entry 4710 (class 2606 OID 49906)
-- Name: rate rate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rate
    ADD CONSTRAINT rate_pkey PRIMARY KEY (id);


--
-- TOC entry 4706 (class 2606 OID 33196)
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


-- Completed on 2025-08-12 17:17:25

--
-- PostgreSQL database dump complete
--

