# Execute on every push or PR to dev
name: Push or PR to dev
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  #-----------------------------------------------------------------------
  #--- Detect the changes
  #-----------------------------------------------------------------------
  changes:
    runs-on: ubuntu-latest
    needs: validate-branch
    if: success()
    outputs:
      user: ${{ steps.filter.outputs.user }}
      book: ${{ steps.filter.outputs.book }}
      review: ${{ steps.filter.outputs.review }}
      api_gateway: ${{ steps.filter.outputs.api_gateway }}
      registry_service: ${{ steps.filter.outputs.registry_service }}
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            user:
              - 'services/user-service/**'
            book:
              - 'services/book-service/**'
            review:
              - 'services/review-service/**'
            api_gateway:
              - 'services/api-gateway/**'
            registry_service:
              - 'services/registry-service/**'
            frontend:
              - 'mflibrary-frontend/**'

  #-----------------------------------------------------------------------
  #--- Test user-service
  #-----------------------------------------------------------------------
  test-user-service:
    needs: changes
    if: needs.changes.outputs.user == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the submodule user-service
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run the user-service tests
        run: |
          chmod +x ./submodules/user-service/mvnw
          ./submodules/user-service/mvnw -f ./submodules/user-service/pom.xml clean test

  #-----------------------------------------------------------------------
  #--- Test book-service
  #-----------------------------------------------------------------------
  test-book-service:
    needs: changes
    if: needs.changes.outputs.book == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the submodule book-service
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run the book-service tests
        run: |
          chmod +x ./submodules/book-service/mvnw
          ./submodules/book-service/mvnw -f ./submodules/book-service/pom.xml clean test

  #-----------------------------------------------------------------------
  #--- Test review-service
  #-----------------------------------------------------------------------
  test-review-service:
    needs: changes
    if: needs.changes.outputs.review == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the submodule review-service
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run the review-service tests
        run: |
          chmod +x ./submodules/review-service/mvnw
          ./submodules/review-service/mvnw -f ./submodules/review-service/pom.xml clean test

  #-----------------------------------------------------------------------
  #--- Test registry-service
  #-----------------------------------------------------------------------
  test-registry-service:
    needs: changes
    if: needs.changes.outputs.registry_service == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the submodule registry-service
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run the registry-service tests
        run: |
          chmod +x ./submodules/registry-service/mvnw
          ./submodules/registry-service/mvnw -f ./submodules/registry-service/pom.xml clean test

  #-----------------------------------------------------------------------
  #--- Test api-gateway
  #-----------------------------------------------------------------------
  test-api-gateway:
    needs: changes
    if: needs.changes.outputs.api_gateway == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the submodule api-gateway
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run the api-gateway tests
        run: |
          chmod +x ./submodules/api-gateway/mvnw
          ./submodules/api-gateway/mvnw -f ./submodules/api-gateway/pom.xml clean test

  #-----------------------------------------------------------------------
  #--- Test mflibrary-frontend
  #-----------------------------------------------------------------------
  test-mflibrary-frontend:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ./mflibrary-frontend

      - name: Run frontend tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
        working-directory: ./mflibrary-frontend
